name: Sync Upstream
on:
  schedule:
  - cron: "0 0 * * 0"  # run once a week
  workflow_dispatch:   # run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
    - uses: exions/merge-upstream@v1
      with:
        upstream: dtolnay/rust-toolchain
        upstream-branch: master
        branch: main


